name: "Run Batch Scraper and Save Files"

on:
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the scraper
        run: |
          python app/batch_scrape.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add scraped_data.json scraped_data.csv
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update scraped data [skip ci]"
            git push origin HEAD:${{ github.ref }}
          else
            echo "No changes to commit."
          fi
